### ISSUE TITLE
Arm shadows and culling

### ISSUE THREAD

**Issue by TwistedModding** [ArranzCNL/ImprovedCameraSE-NG#1]
While weapons drawn, arm shadows disappear when using 1st person arms rather than 3rd.

Near distance is being used to reduce as much clipping as possible, but it has it's downsides, color discrepancies at certain angles depending on the value of near distance.

This has been known since the mods release for people viewing this. I am making this post to stop it from popping up multiple times.

**Comment by ArranzCNL** [comment]
Near Distance fix is in the works.
* Fixed an engine related bug that stopped fNearDistance:Display from processing when indoors. (MapMenu bug since indoors it switches to Local Map)
* Currently looking into a weird brightness increase when fNearDistance:Display drops below 15.0f when outdoors.

~~Once the brightness issue is resolved fNearDistance modification(s) via the menu/config will be removed.~~

Edit:
Weird brightness issues seem related to shaders which I am unable to fix, logic needs to be updated to them to enforce clamping!

**Comment by ArranzCNL** [comment]
Never going to be implemented.
