### ISSUE TITLE
Camera flicker when looting

### ISSUE THREAD

**Issue by dndak** [ArranzCNL/ImprovedCameraSE-NG#2]
Camera flickers when looting a container if the character above scale 1, height mods, console, etc

Reproduce:
1 open console, click to select character or run command: prid 00000014, run command: setscale 1.2
2 in first person mode loot any barrel chest container, exit the container
3 camera will flicker for a second, like its snapping to scale 1 then again snapping back up to scale 1.2

**Comment by ArranzCNL** [comment]
It does do this due to near distance changing, default game is 15. Under animated/scripted events we reduce this down to 2.0 to resolve clipping issues.

I was having some fun testing this out, needed to crouch to pickup flowers/shrooms on setscale 2.0.

Changing near distance isn't an ideal solution but it is the best we got for now. Hopefully will be resolved in the future!
