### ISSUE TITLE
First person event visual incompability with visual mod

### ISSUE THREAD

**Issue by FraidOfWater** [ArranzCNL/ImprovedCameraSE-NG#6]
While using a mod that increases the player's visual range of movement, (the player can look up and down more than 90 degrees) and then going beyond 90 degrees, the gamma is suddenly increased. For some reason it also seems to reduce clipping seen on the character body during some animations. If you are interested, [here](https://www.mediafire.com/folder/abev0450krzng/Debug) is a mediafire folder containing the plugin I used.

Example video:
https://github.com/ArranzCNL/ImprovedCameraSE-NG/assets/141600613/042ea58c-12cf-433c-9e36-544ec91f9a5e

**Comment by ArranzCNL** [comment]
It is due to fPitchThreshold aka Near Distance (you can alter this), it will be removed once I figure out how to stop the model from being culled.

The current method with near distance causes too many oddities as it is altered willy nilly, I must admit it should be changed at source. (FOV is in the same boat as well currently) As I mentioned rather just fix the culling process instead that way won't need to touch near distance at all then.
